version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/employee-feedback-app

hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ec2-user
